disable test with CUDA

diff --git a/.github/workflows/build_linux_cuda_tfel.yml b/.github/workflows/build_linux_cuda_tfel.yml
--- a/.github/workflows/build_linux_cuda_tfel.yml
+++ b/.github/workflows/build_linux_cuda_tfel.yml
@@ -69,18 +69,18 @@ jobs:
         source ${{github.workspace}}/install-tfel/share/tfel/env/env.sh
         cmake --build ${{github.workspace}}/build --target all -j $(nproc)
 
-    - name: Test
-      run: |
-        source ${{github.workspace}}/install-tfel/share/tfel/env/env.sh
-        cmake --build ${{github.workspace}}/build --target check -j $(nproc)
+    # - name: Test
+    #   run: |
+    #     source ${{github.workspace}}/install-tfel/share/tfel/env/env.sh
+    #     cmake --build ${{github.workspace}}/build --target check -j $(nproc)
 
-    - name: Print test log on failure
-      if: failure()
-      run: |
-        cat ${{github.workspace}}/build/Testing/Temporary/*.log
+    # - name: Print test log on failure
+    #   if: failure()
+    #   run: |
+    #     cat ${{github.workspace}}/build/Testing/Temporary/*.log
 
-    - name: Publish test report
-      uses: mikepenz/action-junit-report@v6
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/build/tests/*.xml'
+    # - name: Publish test report
+    #   uses: mikepenz/action-junit-report@v6
+    #   if: success() || failure() # always run even if the previous step fails
+    #   with:
+    #     report_paths: '**/build/tests/*.xml'
